### ISSUE TITLE
[BUG]: When using joystick, SAS does not function

### ISSUE THREAD

**Issue by coder4432** [Simpit-team/KerbalSimpitRevamped-Arduino#26]
# SAS not functioning when using a joystick

### I am using the "KerbalSimpitThrottleDemo.ino" code as an example from the library, I have attached a potentiometer to the "THROTTLE_PIN" (A0) and an analogue joystick to the "PITCH_PIN" (A1) and "ROLL_PIN" (A2). (All wiring checked and functional). The potentiometer and joystick work perfectly, however when I am using the joystick, the SAS (even if activated in game) is completely non functional, the SAS still affects the Yaw axis, but no other axis.
<br>

### I have tried using without the joystick, and function of the SAS is completely normal (as expected), however when I use the joystick, the used axis's are not adjusted by SAS.
<br>

## To Reproduce:

1. Please provide the code of your controller, to help with diagnosing the issue:
The "KerbalSimpitThrottleDemo.ino" example included with the Arduino library.

2. Please thoroughly explain the most repeatable way that you have found to get the issue you are experiencing to occur:
Just upload the code, attach all the wiring, and attempt a flight with SAS on

### I expected the pitch and roll to be changed by the joystick, and for SAS to function like if used with a keyboard (WASD)
<br>

## Additional context
- `/* KerbalSimpitThrottleDemo

   A demonstration of how to use KerbalSimPit to send throttle 
   or rotation command.

   Assume A0, A1, A2 are plugged on a potentiometer. Each potentiometer will be used
   to control throttle, pitch and roll of you rocket.
   See these links for basic descriptions of how to hook up a potentiometer:
     - https://www.arduino.cc/en/tutorial/potentiometer
     - https://learn.sparkfun.com/tutorials/sparkfun-inventors-kit-experiment-guide---v40/circuit-1b-potentiometer
*/

#include "KerbalSimpit.h"

// Set the pin numbers:
const int THROTTLE_PIN = A0; // the pin used for controlling throttle
const int PITCH_PIN = A1;    // the pin used for controlling pitch
const int ROLL_PIN = A2;     // the pin used for controlling roll

// Declare a KerbalSimpit object that will
// communicate using the "Serial" device.
KerbalSimpit mySimpit(Serial);

void setup() {
  // Open the serial connection.
  Serial.begin(115200);

  // Set initial pin states  
  pinMode(LED_BUILTIN, OUTPUT);
  
  // Turn on the built-in to indicate the start of the handshake process
  digitalWrite(LED_BUILTIN, HIGH); 

  // This loop continually attempts to handshake with the plugin.
  // It will keep retrying until it gets a successful handshake.
  while (!mySimpit.init()) {
    delay(100);
  }
  // Turn off the built-in LED to indicate handshaking is complete.
  digitalWrite(LED_BUILTIN, LOW);
  // Display a message in KSP to indicate handshaking is complete.
  mySimpit.printToKSP("Connected", PRINT_TO_SCREEN);
}

void loop() {
  // Send at each loop a message to control the throttle and the pitch/roll axis.
  
  throttleMessage throttle_msg;
  // Read the value of the potentiometer
  int reading = analogRead(THROTTLE_PIN);
  // Convert it in KerbalSimpit Range
  throttle_msg.throttle = map(reading, 0, 1023, 0, INT16_MAX);
  // Send the message
  mySimpit.send(THROTTLE_MESSAGE, throttle_msg);

  rotationMessage rot_msg;
  // Read the values of the potentiometers
  int reading_pitch = analogRead(PITCH_PIN);
  int reading_roll = analogRead(ROLL_PIN);
  // Convert them in KerbalSimpit range
  int16_t pitch = map(reading_pitch, 0, 1023, INT16_MIN, INT16_MAX);
  int16_t roll = map(reading_roll, 0, 1023, INT16_MIN, INT16_MAX);
  // Put those values in the message
  rot_msg.setPitch(pitch);
  rot_msg.setRoll(roll);
  // Send the message
  mySimpit.send(ROTATION_MESSAGE, rot_msg);
}`

# Thanks for any help!

**Comment by aleopardstail** [comment]
digging into the actual game code this appears to be largely intentional, if not ideal. the default code sends a value between INT16_MIN and INT16_MAX, based on the Arduino analogue input 0-1023. internally the game processes this by taking the player input value, and if its not equal to zero - i.e. at the mod point, using it. if it is at the mid point it doesn't use it.

the result is that if you have SAS enabled it can _only_ function when the joystick is dead centre.

the trouble is its unlikely your joystick reports the dead centre value, 511, when in the middle, its likely a range a bit above or below - hence the game sees an input and uses it.

there are two possible solutions to this, one is to modify the code on the arduino to add a "dead band" in the centre, so any value +/- a given range from 511 is reported as 511, then the game will see that as a zero input and let SAS do its thing. - Ideally the examples need to be adjusted to account for this or at least include a comment.

the second method would be to change the code in the game so instead of using either the SAS or player input, it combines them - this can be added in the "AxisControl.cs" file by changing how the function "AutopilotUpdate()" works to not simply use one value or the other but to blend them in some way.

I have tested some very basic code that will take both values, and if both go in the same direction, use the one with the larger magnitude, and if they oppose each other will take a weighted average (player input tested at 75%), so the player can override SAS but not totally when its active

**Comment by aleopardstail** [comment]
as an example of how to add a deadzone to the example consider the following:

`rot_msg.setPitch(JoystickRemap(analogRead(A1), 40, false));`

this calls a custom function to process the analogue input to something suitable, this function is as follows

```
// remap joystick inputs to suitable range with deadband and inversion support
int16_t JoystickRemap(uint16_t Value, uint8_t Deadband, bool Invert)
{
  int16_t R = 0;

  // first apply the deadband code to the input value
  if (Value <= (511 - Deadband))
  {
    R=Value;
  }
  else if (Value >= (511 + Deadband))
  {
    R=Value;
  }
  else
  {
    R=511;
  }

  // now apply the actual mapping
  if (R == 511)
  {
    // if in the deadband we ensure the output value is zero to centre the axis
    R = 0;
  }
  else
  {
    if (Invert == true)
    {
      R = map(R, 0, 1023, INT16_MAX, INT16_MIN);
    }
    else
    {
      R = map(R, 0, 1023, INT16_MIN, INT16_MAX);
    }
  }

  return R;
}
```

you can specify the size of the desired deadband and if the axis should be inverted

**Comment by coder4432** [comment]
That's worked perfectly, thanks for your help!
